name: my_editor_app
description: My Editor App by Speedy
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  http: ^1.2.2
  video_player: ^2.9.1
  image_picker: ^1.1.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
